services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rrcompanion
      MYSQL_USER: rrcompanion
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
