service: rrcompanion-scraping

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-west-2'}
  timeout: 900 # Maximum Lambda timeout (15 minutes)
  memorySize: 2048 # 2GB memory for better performance
  environment:
    NODE_ENV: ${self:provider.stage}
    DATABASE_URL: ${env:DATABASE_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds:*
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::rrcompanion-scraping-${self:provider.stage}/*"

functions:
  # Rising Stars scraping - main page
  # DEPRECATED: 'main' is now included in scrapeRisingStarsAll
  scrapeRisingStarsMain:
    handler: src/handlers/risingStarsMain.handler
    timeout: 900
    memorySize: 2048
    events:
      - schedule:
          rate: rate(15 minutes)
          enabled: false # Disabled - now handled by scrapeRisingStarsAll
    environment:
      SCRAPING_TYPE: "rising-stars-main"

  # Rising Stars scraping - all genres (including 'main')
  scrapeRisingStarsAll:
    handler: src/handlers/risingStarsAll.handler
    timeout: 900
    memorySize: 2048
    events:
      - schedule:
          rate: rate(15 minutes)
          enabled: true
    environment:
      SCRAPING_TYPE: "rising-stars-all"

  # Individual fiction scraping
  scrapeFiction:
    handler: src/handlers/fiction.handler
    timeout: 300
    memorySize: 1024
    environment:
      SCRAPING_TYPE: "fiction"

  # Fiction history scraping
  scrapeFictionHistory:
    handler: src/handlers/fictionHistory.handler
    timeout: 270
    memorySize: 1536
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
    environment:
      SCRAPING_TYPE: "fiction-history"

  # Test fiction scraping (for debugging/auditing)
  testFiction:
    handler: src/handlers/testFiction.handler
    timeout: 300
    memorySize: 1024
    environment:
      SCRAPING_TYPE: "test-fiction"

  # Debug HTML structure (for debugging scraping issues)
  debugHtml:
    handler: src/handlers/debugHtml.handler
    timeout: 300
    memorySize: 1024
    environment:
      SCRAPING_TYPE: "debug-html"

plugins:
  - serverless-offline

build:
  esbuild: true

package:
  exclude:
    - node_modules/**
    - .git/**
    - .env*
    - README.md
    - "*.md"
