name: Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to migrate'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  migrate-database:
    name: Run Database Migration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '1.x'

      - name: Run Database Migration
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "🗄️ Starting database migration for ${{ inputs.environment }}..."
            cd /var/www/rrcompanion
            
            # Pull latest changes
            git pull origin main
            
            # Run the migration
            cd apps/api
            deno run --allow-net --allow-env --allow-read --allow-write src/main.ts
            
            echo "✅ Database migration completed!"
            
            # Show migration status
            echo "📊 Migration status:"
            deno run --allow-net --allow-env --allow-read --allow-write --allow-sql test-migrations.ts 