name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-backend:
    name: Deploy Backend API
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '1.x'

      - name: Test Backend
        run: |
          cd apps/api
          deno test --allow-net --allow-env --allow-read --allow-write

      - name: Deploy Backend to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "🚀 Starting backend deployment..."
            cd /var/www/rrcompanion
            
            # Pull latest changes
            git pull origin main
            
            # Install/update Deno dependencies
            cd apps/api
            deno cache --reload src/main.ts
            
            # Restart the service
            sudo systemctl restart rrcompanion-api
            
            # Check service status
            sudo systemctl status rrcompanion-api --no-pager
            
            echo "✅ Backend deployment completed!"

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend # Wait for backend to deploy first
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd apps/web
          npm ci

      - name: Build Frontend
        run: |
          cd apps/web
          npm run build
        env:
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}

      - name: Deploy Frontend to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "🎨 Starting frontend deployment..."
            cd /var/www/rrcompanion
            
            # Pull latest changes
            git pull origin main
            
            # Install/update dependencies
            cd apps/web
            npm ci
            
            # Build the frontend
            npm run build
            
            # Copy built files to web root
            sudo cp -r dist/* /var/www/html/
            
            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
            
            # Restart Caddy if needed
            sudo systemctl reload caddy
            
            echo "✅ Frontend deployment completed!"

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    
    steps:
      - name: Wait for services to start
        run: sleep 30

      - name: Check Backend Health
        run: |
          echo "🔍 Checking backend health..."
          curl -f ${{ secrets.BACKEND_URL }}/api/health || exit 1
          echo "✅ Backend is healthy!"

      - name: Check Frontend
        run: |
          echo "🔍 Checking frontend..."
          curl -f ${{ secrets.FRONTEND_URL }} || exit 1
          echo "✅ Frontend is accessible!"

      - name: Deployment Summary
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "Backend: ${{ secrets.BACKEND_URL }}"
          echo "Frontend: ${{ secrets.FRONTEND_URL }}" 